# .github/workflows/test.yml

name: Test Build before Publish
on:
  push:
    branches: [dev]

jobs:
  validate-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Only
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          tags: test-build:local
